FACTS_IDENTIFIER = "factscore"
DECONTEXTUALIZED_FACTS_IDENTIFIER = "molecular"

MDS_TASK = "MDS"
LFQA_TASK = "LFQA"

MDS_DATASET = "multinews"
LFQA_DATASET = "evaluating"
TASK_TO_DATASET = {
    "MDS": MDS_DATASET,
    "LFQA": LFQA_DATASET
}

LLM_LAQUER_METHOD = "llm"

HIGHLIGHT_SEP = "<HIGHLIGHT_SEP>"

TRUE_TEACHER_ENTAILMENT_MODEL_IDENTIFIER = "trueteacher"